### ISSUE TITLE
Wasm support

### ISSUE THREAD

**Issue by Uriopass** [Uriopass/Egregoria#22]
Eventually, I want to have an Egregoria client running on wasm, however this is currently blocked on:

- wgpu 0.6 which should go out soon enough
- audio which is just not working in wasm right now I think. There isnt even a audio backend in Egregoria anyway though that would be good since there's already some music.

**Comment by dabreegster** [comment]
Out of curiosity, what's the path for rendering text? Does your stack avoid a dependency on harfbuzz / freetype?

**Comment by Uriopass** [comment]
Well, I don't have any text rendering at the moment ! It all goes through imgui which compiles to wasm (and gives a list of colored triangles) and I don't know what they use to do it portably.

**Comment by Uriopass** [comment]
Still blocked on imgui having complicated wasm (not painless from imgui lib at least) support. Might want to migrate to egui.

**Comment by Uriopass** [comment]
Finally got it to build after migrating to egui. BUT. I still need to figure out how to handle all the I/O.. I can't just use std::fs::read_to_string(). It all needs to be async and be able to download it from a server.

**Comment by dabreegster** [comment]
I'm curious if you find nice solutions for this. When I hit the same difficulty, I started by just statically including all the files as part of the wasm binary using `include_dir`. (https://github.com/evolutics/iftree looks like a more well-maintained option)

https://github.com/a-b-street/abstreet/blob/master/abstio/src/io_web.rs might have some reference code for things like storing player settings in browser local storage, instead of a local file. I tried to make the `abstio` API work the same natively or on WASM, but it's very messy. One of the hardest parts is async loading screens. Async loading could fail, you may want to print a progress bar while it's fetching, etc. I never found anything nice there. Maybe `egui` has some proper support for this kind of pattern?

**Comment by Uriopass** [comment]
I found that when [using bevy](https://uriopass.itch.io/chick-the-dog) for the [rusty jam 2](https://itch.io/jam/rusty-jam-2) their asset pipeline just worked straight out of the box on desktop and on the web.

Basically they have an `AssetServer<T>` that returns a `Handle<T>` which is fetched async, garbage collected using reference counting and can be used by other parts of the engine. So you can render an image using a `Handle<Texture>`, play audio using `Handle<Sound>`, and there's a fallback texture/audio when not loaded.

Sadly that pattern doesn't seem to have been extracted into a crate, the [bevy_web_asset](https://crates.io/crates/bevy_web_asset) depending on bevy itself.

Using local storage does seem useful as it has a sync API, albeit it is limited to 4MB only, so cannot be used for big save file for examples.

I've looked at abstio a bit already, but in the end I think that something asynchronous that can load multiple things at once is quite important for the web where latency is big. Including most of the assets in the binary does seem to be a good idea though, I didn't think of it, I might look into it a bit further.

**Comment by Uriopass** [comment]
I've decided wasm support is not worth it: The game is too heavy, save files can get quite big and multiplayer support would be hell.
